### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Argus1234** [fbdajh/Calculatormon-CE#3]
Found a couple of bugs while playtesting:
1. When picking up the pokeball in the southeast corner of Pallet town, the item will not show up in your inventory. Later, if you press the empty slot in your bag, it will display that you used a pokeball, and that you now own 255 pokeballs. This does not happen again, and this has not been tested to see if it will happen with other items.
2. When entering the only house is map two, the back wall (when pressed) will say that you're viewing a remoteless TV. The same house also has two trees, both of which can be walked over. The house also has an invisible obstacle in the bottom left corner.
3. If Blue defeats you once in Pallet town, he will still battle you again after over and over till you beat him, making it _very_ hard to leave the Town.
4. In Pallet town some house doors will not allow you to enter, but instead display the text "Your house", the same as the sign beside the hero's house.
5. If you have 255 of an item, and you find one more, you will have 0 of that item.
6. In the top right corner of map 2, the item displays "Found a mes" and no "mes" appears in your inventory.
7. When the guy in map 3 tries to give you cut, you won't actually receive cut...
8. When walking toward a person who is walking towards you, they will walk through you. This does not happen if you are stationary.

I look forward to updates, and thanks for reading!

**Comment by KellerWheat** [comment]
I fixed 2, 3, 4, 6, and 8. I am working on 5 right now. I was unable to replicate 1, but it seems to be working normally now. I also could not replicate 7. There is a separate pouch inside the bag for TMs. Did you check there?

**Comment by Argus1234** [comment]
Nice! But some errors are still showing up, and there are new ones.
Yes, problem 7 does not happen. I just didn't realize there was another pouch in your bag. Maybe you should make that easier to notice? It's just a suggestion though, you don't need to do it.
Problem 8 is still happening.
New problems
1. Blue's sister always repeats her message, even though it is no longer important.
2. The tree to the left of Blue's house is non-collidable.
3. When entering the house in map two, you will move very slowly, looking kinda glitchy, before the team rocket thug tells you to leave. You turn around and start leaving very slowly, but so slowly that the thug notices you again. This causes you to turn around and around in an infinite loop, freezing the game until you quit.
4. In map 2 in the top left corner, the pokeball is non-collidable, and does not contain anything.
3. In map two, the water is non-collidable, but I don't know if this is intentional or not.
5. In all the maps, if you go off the edge that is not at a pre-designed exit, you will disappear until you walk back.

**Comment by KellerWheat** [comment]
I fixed all the new problems you listed and added arrows to the bag to make the TM pouch easier to notice. I cannot get NPCs to walk through the player. Can you give me more details?

**Comment by Argus1234** [comment]
I'm not sure exactly why this is. happening but it seems to happen only when the player and npc walk cycles correspond so that they both exactly start stepping toward a tile before they can even sense collision. The point is they seem to both step on the tile at the same time. This makes it pretty hard to replicate, but it is possible. Thanks!

**Comment by KellerWheat** [comment]
For some reason I cannot get this glitch to occur. Sorry to ask for this, but can you record it and send me the video?

**Comment by Argus1234** [comment]
Sorry for replying late. I try to get the screenshots soon, but I can't do it for a bit as my computer that has the recording software crashed and I have to take it to service. The software cannot be downloaded on my current computer because it is blocked. I should be able to get you a screen record tomorrow or after tomorrow.
